wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: basique
epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714549872.0
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
